---
- name: Rotate current SSH user's password and save to Bitwarden
  hosts: all
  become: true
  vars:
    ssh_user: "{{ lookup('file', '.bw_temp/username.txt') }}"
    new_password: "{{ lookup('file', '.bw_temp/password.txt') }}"
  tasks:
    - name: Change current user's password
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
